name: module pipeline trigger

trigger:
  branches:
    include:
    - main

pool:
  name: selfhosted

jobs:
- job: TriggerPipelineB
  steps:

  - script: echo 'trigger pipeline'
    displayName: 'trigger pipeline'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'id-platformiac-nonprod-sc-01'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
            az pipelines run --branch 'refs/heads/main' --name 'trigger-pipeline' --project 'tuttu' --org 'https://dev.azure.com/tuttu'

