name: 'Resource Module Publish'
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/resources/*.bicep

pool:
  name: 'selfhosted'

parameters:
- name: azureServiceConnection
  type: string
  default: 'id-platformiac-nonprod-sc-01'

jobs:
- job: 
  displayName: 'Push Resource Modules'
  steps:
    - checkout: self
      clean: true
      fetchDepth: 2   
      persistCredentials: true
      displayName: 'Get checkout'

    - task: AzurePowerShell@5
      displayName: Git diff on resources modules
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnection }}'
        scriptType: filePath # | 'InlineScript'
        scriptPath: $(Build.SourcesDirectory)/pipelines/scripts/Get-Git-Diff-Files.ps1
        # scriptPath: $(Build.SourcesDirectory)/pipelines/scripts/check-get-diff.ps1
        scriptArguments:
          -gitDiffPath 'modules/resources/*.bicep'
          # -gitDiffPath 'modules/resources/*.bicep'
        azurePowerShellVersion: latestVersion
        FailOnStandardError: true
        errorActionPreference: 'stop' # | 'stop' | 'continue' | 'silentlyContinue'
        pwsh: true
