name: 'Resource Module Publish'
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/resources/*/*.bicep

pool:
  name: 'selfhostedvm'

parameters:
- name: azureServiceConnection
  type: string
  default: 'id-platformiac-nonprod-sc-01'

jobs:
- job: 
  displayName: 'Push Resource Modules'
  steps:
    - checkout: self
      clean: true
      fetchDepth: 2   
      persistCredentials: true
      displayName: 'Get checkout'

    - script: |
        if command -v docker &> /dev/null
          then
        echo "Docker is already installed."
          docker --version   # Optional: Print Docker version
        else
        echo "Docker is not installed."
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        fi
      displayName: 'Install Docker'

    - script: |
        # sudo dpkg --configure -a
        # sudo apt-get update
        sudo usermod -aG docker $(whoami)
        # docker run hello-world
        # echo "Added $CURRENT_USER to the docker group."
        # groups $(whoami)
      displayName: 'Add user'

    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnection }}'
        inlineScript: |
          az --version
          az account show

    - task: AzurePowerShell@5
      displayName: Git diff on resources modules
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnection }}'
        scriptType: filePath # | 'InlineScript'
        scriptPath: $(Build.SourcesDirectory)/pipelines/scripts/main.ps1
        scriptArguments:
          -acrName 'tuttuacrplatformiacsc01'
          -gitDiffPath 'modules/resources/*/*.bicep'
        azurePowerShellVersion: latestVersion
        FailOnStandardError: true
        errorActionPreference: 'stop' # | 'stop' | 'continue' | 'silentlyContinue'
        pwsh: true
