name: 'Bicep Module Publish'
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/resources/*

pool:
  name: 'selfhosted'

parameters:
- name: azureServiceConnection
  type: string
  default: 'id-platformiac-nonprod-sc-01'

jobs:
- job: 
  displayName: 'Push Modules'
  steps:
    - checkout: self
      clean: true
      fetchDepth: 1   
      persistCredentials: true
      displayName: 'Get checkout'

    - task: AzurePowerShell@5
      displayName: Git diff on modules
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnection }}'
        scriptType: filePath # | 'InlineScript'
        scriptPath: $(Build.SourcesDirectory)/pipelines/scripts/check-get-diff.ps1
        # scriptArguments:
        #   -Arg1 val1 `
        #   -Arg2 val2 `
        #   -Arg3 val3
        azurePowerShellVersion: latestVersion
        FailOnStandardError: true
        errorActionPreference: 'stop' # | 'stop' | 'continue' | 'silentlyContinue'
        pwsh: true
