trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - modules/*
    # - pipelines/*

resources: 
  - repo: self

pool:
  name: 'selfhosted'

variables:
  - name: pathVersion
    value: $[counter(0, 0)] # dont know what is this for
  # - template: variables/variables-test.yaml

jobs:
  - job: bicep_build
    steps:
      - checkout: self # This step is redundant (pipelines default beheviour in first step)
        persistCredentials: true
        clean: true
        fetchDepth: 0
      - task: AzurePowerShell@5
        name: bicepBuildTrigger
        env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        inputs:
            displayName: 'Triggering bicep build for changed files'
            ScriptType: filePath
            ScriptPath: $(Build.SourceDirectory)/pipelines/scripts/trigger_pipeline.ps1
            failOnStderr: true
            azurePowerShellVersion: "LatestVersion"
            azureSubscription: ${{ variables.azureSubscriptionName}}
            pwsh: true
            ScriptArgument: > # Use this to avoid newline characters in multilines string
                -patchVersion $(patchVersion)
                -pipelineName "build-and-publish-module"
                -bicepVersionFile "metadata.json"
                -bicepFile "main.bicep"
