trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - modules/*
    # - pipelines/*

resources: 
  - repo: self

pool:
  name: 'selfhosted'

variables:
  - name: pathVersion
    value: $[counter(0, 0)] # dont know what is this for
  # - template: variables/variables-test.yaml

jobs:
  - job: bicep_build
    steps:
      - script: |
            echo 'testing script'
            ls 
            pwd 
            echo 'pwd done'
            echo 'echo SourceDirectory'
            echo $(Build.SourceDirectory)
            echo 'System Access Token'
            echo $(System.AccessToken)
      - checkout: self # This step is redundant (pipelines default beheviour)
        persistantCredential: true
        clean: true
        fetchDepth: 0
    # - task: AzurePowerShell@5
    #     name: bicepBuildTrigger
    #     env:
    #       SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    #     inputs:
    #       ScriptType: filePath
    #       ScriptPath: $(Build.SourceDirectory)/pipelines/scripts/trigger_pipeline.ps1
    #       failOnStderr: true
    #       azurePowerShellVersion: "LatestVersion"
    #       azureSubscription: ${{ variables.azureSubscriptionName}}
    #       pwsh: true
    #       ScriptArgument
