trigger:
  branches:
    include:
    - main
  path:
    exclude:
    - modules
    - pipelines

resources: 
  - repo: self

pool:
  name: 'selfhosted'

variables:
  - name: pathVersion
    value: $[counter(0, 0)] # dont know what is this for
  # - template: variables/variables-test.yaml

jobs:
  - job: bicep_build
    steps:
    - checkout: self
      persistantCredentials: true
      clean: true
      fetchDepth: 0
    - script: | 
        echo "BigBicep"
        echo ls
        echo pwd

    # - task: AzurePowerShell@5
    #   name: bicepBuildTrigger
    #   env:
    #     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    #   inputs:
    #     ScriptType: filePath
    #     ScriptPath: $(Build.SourceDirectory)/pipelines/scripts/trigger_pipeline.ps1
    #     failOnStderr: true
    #     azurePowerShellVersion: "LatestVersion"
    #     azureSubscription: ${{ variables.azureSubscriptionName}}
    #     pwsh: true
    #     ScriptArgument
